{% set name = "bw2temporalis" %}
{% set version = "1.0rc3" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "7f79c3c351636edbf82182399185868f047fc3917c5b20061f8e17be4bf2a43e" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - brightway2 >=2.1.1
    - bw2data >=3.0
    - bw2calc
    - bw2io >=RC3
    - bw2speedups >=2.2
    - numpy >=1.6
    - scipy
    - numexpr
  run:
    - python
    - brightway2 >=2.1.1
    - bw2data >=3.0
    - bw2calc
    - bw2io >=RC3
    - bw2speedups >=2.2
    - numpy >=1.6
    - scipy
    - numexpr

test:
  imports:
    - bw2temporalis
    - bw2temporalis.dyn_methods
    - bw2temporalis.examples
    - bw2temporalis.tests

about:
  home: https://bitbucket.org/cardosan/brightway2-temporalis
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: Provide a dynamic LCA calculations for the Brightway2 life cycle assessment framework
  description: 'Brightway2 temporalis

    =====================


    This package provides a dynamic (i.e. varying in time) LCA calculations for the `Brightway2 life cycle assessment framework <https://brightwaylca.org>`_. `Online documentation <https://brightway2-temporalis.readthedocs.io/en/latest/>`_
    is available, and the source code is hosted on `Bitucket <https://bitbucket.org/cmutel/brightway2-temporalis>`_.

    '
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
