{% set name = "bw2temporalis" %}
{% set version = "1.0" %}
{% set file_ext = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash_value = "dbf0374426f43b18e4c84b44a0d5337780b47c97120331f7d9c4427a8b76072d" %}

package:
  name: '{{ name|lower }}'
  version: '{{ version }}'

source:
  fn: '{{ name }}-{{ version }}.{{ file_ext }}'
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ file_ext }}
  '{{ hash_type }}': '{{ hash_value }}'

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  host:
    - python
    - setuptools
    - brightway2 >=2.1.1
    - bw2data >=3.0
    - bw2calc
    - bw2io >=RC3
    - bw2speedups >=2.2
    - numpy >=1.6
    - scipy
    - numexpr
  run:
    - python
    - brightway2 >=2.1.1
    - bw2data >=3.0
    - bw2calc
    - bw2io >=RC3
    - bw2speedups >=2.2
    - numpy >=1.6
    - scipy
    - numexpr

test:
  imports:
    - bw2temporalis
    - bw2temporalis.dyn_methods
    - bw2temporalis.examples
    - bw2temporalis.tests

about:
  home: https://bitbucket.org/cardosan/brightway2-temporalis
  license: BSD License
  license_family: BSD
  license_file: ''
  summary: Provide a dynamic LCA calculations for the Brightway2 life cycle assessment framework
  description: ".. ~\n.. ~.. image:: https://ci.appveyor.com/api/projects/status/aiccd0gega0v7suq/branch/default?svg=true\n.. ~\t:target: https://coveralls.io/bitbucket/cardosan/brightway2-temporalis2_delete?branch=master\n\
    .. ~\t:alt: bw2temporalis appveyor build status\n.. ~\n.. ~.. image:: https://coveralls.io/repos/bitbucket/cardosan/brightway2-temporalis2_delete/badge.svg?branch=master\n.. ~\t:target: https://coveralls.io/bitbucket/cardosan/brightway2-temporalis2_delete?branch=master\n\
    .. ~    :alt: Test coverage report\n\n.. image:: https://ci.appveyor.com/api/projects/status/bfyb3bs48fnkful3?svg=true\n    :target: https://ci.appveyor.com/project/cardosan78214/brightway2-temporalis\n\
    \    :alt: bw2temporalis appveyor build status\n\n.. image:: https://coveralls.io/repos/bitbucket/cardosan/brightway2-temporalis/badge.svg?branch=default\n    :target: https://coveralls.io/bitbucket/cardosan/brightway2-temporalis?branch=default\n\
    \    :alt: Test coverage report\n    \n.. image:: https://readthedocs.org/projects/temporalis/badge/?version=latest\n    :target: http://temporalis.readthedocs.io/en/latest/?badge=latest\n    :alt:\
    \ Documentation Status\n\nBrightway2 temporalis\n=====================\n\nThis package provides a dynamic (i.e. varying in time) LCA calculations package for the `Brightway2 life cycle assessment framework\
    \ <https://brightwaylca.org>`_. \n\n`Online documentation <http://temporalis.readthedocs.io/en/latest/>`_ is available, and the source code is hosted on `Bitucket <https://bitbucket.org/cardosan/brightway2-temporalis>`_.\n"
  doc_url: ''
  dev_url: ''

extra:
  recipe-maintainers: ''
